version: 2.1
orbs:
  heroku: circleci/heroku@dev:alpha
  orb-tools: circleci/orb-tools@9.0
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
      build:

      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [10.x, 12.x, 14.x, 15.x]

      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      