version: 2.1

aliases:
  - &restore-cache
    restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
  - &install-deps
    run:
        name: Install dependencies
        command: npm ci
  - &build-packages
    run:
        name: Build
        command: npm run build
  - &run-unit-tests
    run:
        name: Test
        command: npm run test
orbs:
  heroku: circleci/heroku@dev:alpha
  orb-tools: circleci/orb-tools@9.0 
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
      
      