version: 2.1
orbs:
  heroku: circleci/heroku@dev:alpha
  orb-tools: circleci/orb-tools@9.0
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
  steps:
    - run:
        name: run node tests
        command: npm run test    